services:
  # Web Service
  - type: web
    name: melt-challenge-app
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run docker-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOPIFY_APP_URL
        sync: false
      - key: SCOPES
        value: write_products,read_customers,write_customers,write_files
      - key: SHOPIFY_MULTIPASS_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: melt-challenge-db
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

databases:
  - name: melt-challenge-db
    databaseName: melt_challenge
    plan: free
    user: melt_challenge_user
