# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cec3b0930afab043aa73ba47c552b117"
name = "melt-challenge.app"
application_url = "https://noncotyledonal-kenley-motivative.ngrok-free.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://example.com/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://example.com/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://noncotyledonal-kenley-motivative.ngrok-free.dev/auth/callback"
]
