# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cec3b0930afab043aa73ba47c552b117"
name = "melt-challenge.app"
application_url = "https://noncotyledonal-kenley-motivative.ngrok-free.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,write_files"

[auth]
redirect_urls = [
  "https://noncotyledonal-kenley-motivative.ngrok-free.dev/auth/callback"
]
